services:
  backend:
    build: ./Server
    restart: always
    env_file: ./Server/.env
    ports:
      - "8000:8000"
    networks:
      - tecxell-net

  frontend:
    build: ./Client
    restart: always
    ports:
      - "9000:80" 
    depends_on:
      - backend
    networks:
      - tecxell-net

networks:
  tecxell-net:
    driver: bridge
