name: Deploy Tecxell26 to Production

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: self-hosted 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Copy existing .env files
        run: |
          # Copy backend .env
          cp /home/mediaclub-backend2/Tecxell26/Server/.env ./Server/.env
          
          # Copy frontend .env
          cp /home/mediaclub-backend2/Tecxell26/Client/.env ./Client/.env

      - name: Deploy with Docker Compose
        run: |
          # The --build flag ensures the React app is re-compiled with the injected .env variables
          docker compose up --build -d
          
          docker image prune -f
